set(__QT_DEPLOY_TARGET_JobApplicationManager_FILE /Users/pyoungjinji/resume_manager/qt_resume/qt_resume/cmake-build/Debug/JobApplicationManager.app/Contents/MacOS/JobApplicationManager)
set(__QT_DEPLOY_TARGET_JobApplicationManager_TYPE EXECUTABLE)
